-- Library owns series metadata, reader reactions and uploaded article images.
CREATE TABLE library_series (
  user_id bigint NOT NULL REFERENCES registered_users(id) ON DELETE CASCADE,
  name varchar(120) NOT NULL,
  description varchar(2000) NOT NULL DEFAULT '',
  PRIMARY KEY(user_id, name)
);
INSERT INTO library_series(user_id,name)
SELECT DISTINCT user_id,series FROM library_articles WHERE series IS NOT NULL;
CREATE TABLE library_likes (
  article_id bigint NOT NULL REFERENCES library_articles(id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES registered_users(id) ON DELETE CASCADE,
  PRIMARY KEY(article_id,user_id)
);
CREATE TABLE library_bookmarks (
  article_id bigint NOT NULL REFERENCES library_articles(id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES registered_users(id) ON DELETE CASCADE,
  inserted_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(article_id,user_id)
);
CREATE INDEX library_bookmarks_user ON library_bookmarks(user_id,inserted_at DESC);
CREATE TABLE library_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES registered_users(id) ON DELETE CASCADE,
  image bytea NOT NULL CHECK(octet_length(image) BETWEEN 1 AND 2000000),
  content_type text NOT NULL CHECK(content_type IN ('image/jpeg','image/png')),
  inserted_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX library_images_user ON library_images(user_id,inserted_at);
