import { chromium, expect } from "@playwright/test"
import { mkdir } from "node:fs/promises"
const origin = "http://127.0.0.1:4094"
const output = "/app/docs/design/geo-chat/verification/live"
await mkdir(output, { recursive: true })
const browser = await chromium.launch({ headless: true })
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 } })
  const page = await context.newPage()
  const googleErrors: string[] = []
  page.on("console", (msg) => {
    const match = /Google Maps JavaScript API error: (\w+)/u.exec(msg.text())
    if (match?.[1]) googleErrors.push(match[1])
  })
  await page.goto(origin)
  await page.locator("#entrance-nickname").fill("geo-live-" + Date.now().toString().slice(-6))
  await page.locator("#enter-chat").click()
  await expect(page.locator("#chat-room")).toHaveAttribute("data-chat-joined", "true")
  await page.locator("#message-body").fill("/гео")
  await page.locator("#send-message").click()
  await expect(page.getByRole("button", { name: "Начать игру", exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Начать игру", exact: true }).click()
  await expect(page.locator("#geo-answer")).toBeVisible({ timeout: 60000 })
  await expect(page.locator(".geo-return")).toBeEnabled({ timeout: 25000 })
  await expect(page.locator(".geo-panorama .gm-style")).toBeVisible()
  await expect(page.locator(".geo-time")).toHaveText(/0[45]:[0-5][0-9]/)
  await page.screenshot({ path: output + "/desktop-place.png" })
  console.log("PASS real community game preparation and interactive Street View")
  await page.getByRole("button", { name: "Карта", exact: true }).click()
  await expect(page.locator(".geo-google-map .gm-style")).toBeVisible({ timeout: 20000 })
  await expect(page.locator(".gm-err-container")).toHaveCount(0)
  await expect(page.locator(".geo-google-map img").first()).toBeVisible({ timeout: 10000 })
  const map = page.locator(".geo-google-map")
  const box = await map.boundingBox()
  if (!box) throw new Error("Map has no bounds")
  await map.click({ position: { x: box.width / 2, y: box.height / 2 } })
  await page.screenshot({ path: output + "/map-after-click.png" })
  console.log("Google error codes:", googleErrors)
  await expect(page.locator(".geo-map-message")).not.toContainText("Определяем место…", { timeout: 15000 })
  console.log("Map result:", await page.locator(".geo-map-message").textContent())
  await expect(page.locator("#geo-answer")).not.toHaveValue("", { timeout: 15000 })
  await page.screenshot({ path: output + "/desktop-map.png" })
  await page.getByRole("button", { name: "Ответить", exact: true }).click()
  await expect(page.locator(".geo-answer-saved")).toBeVisible()
  await page.reload()
  await page.locator(".geo-mini").click()
  await expect(page.locator(".geo-answer-saved")).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator(".geo-tabs")).toBeHidden()
  await expect(page.locator(".geo-return")).toBeEnabled({ timeout: 25000 })
  await page.screenshot({ path: output + "/mobile-place.png" })
  if (googleErrors.length) throw new Error(googleErrors.join(", "))
  console.log("PASS live Google map selection, geocoding, private answer, reload and mobile")
} finally {
  await browser.close()
}
