import { expect, type Page } from "@playwright/test"

export async function verifyTypingPreference(viewer: Page, writer: Page, observer: Page) {
  await viewer.locator("#toggle-settings").click()
  await expect(viewer.locator("#show-typing")).toBeChecked()
  await viewer.locator("#show-typing").uncheck()
  await viewer.locator("#save-preferences").click()
  await expect(viewer.locator("#settings-modal")).toHaveCount(0)
  await viewer.reload()
  await expect(viewer.locator("#chat-room")).toHaveAttribute("data-chat-joined", "true")
  await viewer.locator("#toggle-settings").click()
  await expect(viewer.locator("#show-typing")).not.toBeChecked()
  await viewer.locator("#close-settings").click()
  await writer.locator("#message-body").pressSequentially("Проверка набора текста", { delay: 120 })
  await expect(observer.locator("#typing-indicator")).toContainText("browser-guest-two")
  await expect(viewer.locator("#typing-indicator")).toBeEmpty()
  await viewer.locator("#message-body").fill("Мой набор по-прежнему виден")
  await expect(writer.locator("#typing-indicator")).toContainText("browser-guest-one")
  await viewer.locator("#message-body").fill("")
  await writer.locator("#message-body").fill("")
  await viewer.locator("#toggle-settings").click()
  await viewer.locator("#show-typing").check()
  await viewer.locator("#save-preferences").click()
  await expect(viewer.locator("#settings-modal")).toHaveCount(0)
  await writer.locator("#message-body").pressSequentially("Снова показываем набор", { delay: 120 })
  await expect(viewer.locator("#typing-indicator")).toContainText("browser-guest-two")
  await writer.locator("#message-body").fill("")
  await expect(viewer.locator("#typing-indicator")).toBeEmpty()
}
