package postgres

import "testing"

func TestRegistrationFingerprintMatchesPhoenix(t *testing.T) {
	// Fixtures generated by :erlang.term_to_binary({:ip, tuple}) and :crypto.hash
	// in the checked-out legacy runtime, including IPv6 INTEGER_EXT segments.
	for address, expected := range map[string]string{
		"127.0.0.1":        "d85qYJRlAUAoZAjge7T4Fg0U1RHmCMH2sULyi58WjMg",
		"192.168.1.10":     "3283wAK4gQ76ARFL8VT8nw_azeBK9NbhZBLDHXegOzY",
		"::1":              "d7aJ8FW0FbVvN2WcVXm7uFUFDk2RGsKdE7zq6XHZbEw",
		"2001:db8:ffff::1": "UW6VCM5sZuFWyMcZwtQuKUu-yoqqsleHvhv2-VUEIm4",
	} {
		actual, err := registrationFingerprint(address)
		if err != nil || actual != expected {
			t.Errorf("%s: got %q err=%v", address, actual, err)
		}
	}
	if _, err := registrationFingerprint("untrusted"); err == nil {
		t.Fatal("invalid peer accepted")
	}
}
